Repository softDsim/softDsim, pull requests merged in 2022-04, with the labels that each got.

#43 task: #42 Use docker compose for mongo
  .gitignore
  database/docker-compose.yml
  mongo_models.py
  mongosetup.docker
  softDsim/settings.py
Labels: enhancement

#47 Feature: #44 central configuration management
  .github/workflows/django.yml
  config.py
  database/docker-compose-gh.yml
  mongo_models.py
  requirements.txt
  softDsim/settings.py
  tests/test_util/test_config.py
Labels: enhancement

#51 task: #50 enable cloud database in config
  config.py
  mongo_models.py
  tests/test_util/test_config.py
Labels: task

#62 Feature: 55 configure python logging
  app/src/team.py
  app/views/app.py
  app/views/rest.py
  app/views/user.py
  app/views/util.py
  mongo_models.py
  softDsim/settings.py
  tests/test_api/test_api.py
Labels: feature, Backend

#71 task: #69 Creating initial react app
  .gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: Frontend

#66 feature: #65 Added REST API test endpoint
  app/api/endpoint_test.py
  app/api_endpoints.py
  softDsim/urls.py
Labels: feature, Backend

#64 Task: 63 Create simple Logo and added it as Favicon
  app/static/app/favicon.ico
  app/templates/app/base.html
  img/logo/logo_192.png
  img/logo/logo_2000.png
  img/logo/logo_500.png
Labels: task

#77 Feature: #76 Added GET Scenario List Endpoint
  app/api/scenario.py
  app/api_endpoints.py
  docs/api/rest.md
  docs/conf.py
  docs/index.rst
  mongo_models.py
Labels: Backend
